name: unittest
on:
  pull_request:
  workflow_dispatch:
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: get python version
        run: python -V
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: unittest for python
        run: python -m unittest discover tests
